### ISSUE TITLE
Complete Equipment Type functionality

### ISSUE THREAD

**Issue by aaronstrickland81** [GTInventory/IMS#28]
Equipment Type functionality has a skeleton frontend, but functionality still needs implemented.

## Tasks
- [ ] On creation of new equipment type, save the following:
- List of attributes assigned to equipment type
- ID of attribute which should be used as the types unique identifier (Possibly the top of the list? Just make sure it is intuitive to the user, we can discuss if needed)
- For each attribute in the list - required/suggested/optional, and unique for type
- [ ] On opening the add equipment type pop-up, the attribute search should hold some results (ideally with paging, but this may be later implemented)
- [ ] On successful creation, the user should be informed that it succeeded and should be taken to the equipment type detail page
- [ ] Test and confirm it acts as it should - correct/add any other functionality which seems unintuitive or incomplete.

**Comment by suprabhatgurrala** [comment]
Basic add functionality has been implemented, but required some changes that broke the edit page.
