### ISSUE TITLE
Project Management miscellany

### ISSUE THREAD

**Issue by aaronstrickland81** [GTInventory/IMS#5]
## Tasks:
- [x] Set up team's TSquare site
- [x] Document meeting minutes on team site
- [x] Ensure all team's work for the sprint is documented in ZenHub appropriately
- [x] Communicate with client
- [x] Organize meetings
