### ISSUE TITLE
As an IT administrator, I want to define a new equipment type so that it can be used throughout the system.

### ISSUE THREAD

**Issue by aaronstrickland81** [GTInventory/IMS#7]
## Task/Story Details
- [ ] Create a "manage equipment types" page, accessible from the menu bar.
- [ ] Create a page accessible from the "manage equipment types" page which allows the user to add an equipment type.

## Acceptance Criteria
- [x] The application contains a page where the user can manage equipment types that is accessible from the main page. This page contains an “Add Equipment Type” page within it.
- [ ] The “Add Equipment Type” page has a "Name" field, which does not accept invalid characters.
- [ ] On the "Add Equipment Type" page, the user can select one or more attributes from those that have been created in the system to assign to the equipment type.
- [ ] A user can mark each attribute assigned to an equipment type as "Required", "Suggested", or "Optional".
- [ ] A user can define an attribute as the identifying attribute for the Equipment Type.
- [x] A user can define which attributes appear in the search results table for the Equipment Type, and in which order they appear.
- [x] When the user selects “Create Equipment Type”, if the name field is filled in and there is no equipment type with this name already, then a new equipment type with the given information is created.
- [ ] When the user selects “Create Equipment Type”, if the given name already exists as an equipment type, it should display a pop-up that informs the user of the already existing equipment type. The Equipment Type creation should not be successful.
